BASE = ../../../rai

DEPEND = Core Kin Gui Geo KOMO Optim

TORCH = 1
BULLET = 1

LIBS += -lhdf5_serial -lhdf5_cpp
CPATHS += /usr/include/hdf5/serial

OBJS = main.o dataGen.o pushingEnvironment.o

include $(BASE)/build/generic.mk
